import { compose, withState } from 'recompose';

import GridView from './GridsView';

const listData = [
  {
    id: 1,
    brand: 'Einstein',
    title: 'meeting room',
    subtitle: 'Limited Edition',
    price: '12:00',
    badge: 'NEW',
    badgeColor: '#3cd39f',
    image:
      'https://i.ibb.co/vV7yp07/salle.jpg',
  },
  {
    id: 2,
    brand: 'Diderot',
    title: 'interview room',
    subtitle: 'Office, prom or special parties ,meeting',
    price: '13:00',
    priceFrom: true,
    image: 'https://i.ibb.co/GxZZqWz/salle2.jpg',
  },
  {
    id: 3,
    brand: 'Voltaire',
    title: 'meeting room',
    subtitle: 'Office, prom or special parties ,meeting',
    price: '08:00',
    priceFrom: true,
    badge: 'Libre',
    badgeColor: '#ee1f78',
    image: 'https://i.ibb.co/87bRmTF/salle3.jpg',
  },
  {
    id: 4,
    brand: 'Freud',
    title: 'dining room',
    subtitle: 'Limited Edition',
    price: '09:00',
    badge: 'NEW',
    badgeColor: 'green',
    image: 'https://i.ibb.co/PQb16pt/salle4.jpg',
  },
  {
    id: 5,
    brand: 'Newton',
    title: 'interview room',
    subtitle: 'Office, prom or special parties ,meeting',
    price: '13:00',
    priceFrom: true,
    image: 'https://i.ibb.co/jr0kp3x/saal1.jpg',
  },
  {
    id: 6,
    brand: 'Perry',
    title: 'meeting room',
    subtitle: 'Office, prom or special parties ,meeting',
    price: '11:00',
    priceFrom: true,
    badge: 'Libre',
    badgeColor: 'red',
    image: 'https://i.ibb.co/ZhrFxdH/salle7.jpg',
  },
  {
    id: 7,
    brand: 'Newton',
    title: 'conference room',
    subtitle: 'Limited Edition',
    price: '9:30',
    badge: 'NEW',
    badgeColor: '#3cd39f',
    image: 'https://i.ibb.co/jr0kp3x/saal1.jpg',
  },
  {
    id: 8,
    brand: 'Einshtein',
    title: 'interview room',
    subtitle: 'Office, prom or special parties ,meeting',
    price: '14:00',
    priceFrom: true,
    image: 'https://i.ibb.co/Xyx4XYZ/Libre.jpg',
  },
  {
    id: 9,
    brand: 'Mad Perry',
    title: 'dining room',
    subtitle: 'Office, prom or special parties interview',
    price: '16:30',
    priceFrom: true,
    badge: 'Libre',
    badgeColor: '#ee1f78',
    image: 'https://i.ibb.co/PQb16pt/salle4.jpg',
  },
  {
    id: 10,
    brand: 'Rose',
    title: 'living room',
    subtitle: 'Limited Edition',
    price: '14:15',
    badge: 'NEW',
    badgeColor: 'green',
    image: 'https://i.ibb.co/YXjwJ0G/salle5.jpg',
  },
  {
    id: 11,
    brand: 'Diderot',
    title: 'interview room',
    subtitle: 'Office, prom or special parties ',
    price: '14:34',
    priceFrom: true,
    image: 'https://i.ibb.co/SxxNX8f/saale1.jpg',
  },
  {
    id: 12,
    brand: 'Mad Diderot',
    title: 'living room',
    subtitle: 'Office, prom or special parties ,meeting',
    price: '14:50',
    priceFrom: true,
    badge: 'Libre',
    badgeColor: 'red',
    image: 'https://i.ibb.co/Xyx4XYZ/Libre.jpg',
  },
];

export default compose(
  withState('tabIndex', 'setTabIndex', 0),
  withState('tabs', 'setTabs', ['Salle', 'List Salle M', 'List Salle P']),
 // withState('data', 'setData', listData),
)(GridView);
